"""Initial migration with cascade delete support

Revision ID: ecec4e04f52d
Revises: 
Create Date: 2025-04-15 10:59:13.711682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecec4e04f52d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clock_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_type', sa.String(length=20), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('clock_in_time', sa.DateTime(), nullable=True),
    sa.Column('clock_out_time', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('school_name', sa.String(length=100), nullable=False),
    sa.Column('school_start_time', sa.Time(), nullable=False),
    sa.Column('school_finish_time', sa.Time(), nullable=False),
    sa.Column('route_start_time', sa.Time(), nullable=True),
    sa.Column('route_finish_time', sa.Time(), nullable=True),
    sa.Column('required_vehicle_size', sa.String(length=50), nullable=True),
    sa.Column('commute_time', sa.Integer(), nullable=True),
    sa.Column('school_postcode', sa.String(length=20), nullable=True),
    sa.Column('escort_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('badge_renewal_date', sa.Date(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('base_postcode', sa.String(length=20), nullable=True),
    sa.Column('shift', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('escorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('base_postcode', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_type', sa.String(length=20), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inset_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_type', sa.String(length=20), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mechanic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('missed_clock_in_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_type', sa.String(length=20), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('requested_time', sa.Time(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missed_clock_out_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_type', sa.String(length=20), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('requested_time', sa.Time(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('non_school_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('tariff', sa.String(length=50), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariff_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('tariff', sa.String(length=50), nullable=False),
    sa.Column('rate_per_mile', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=50), nullable=False),
    sa.Column('make_model', sa.String(length=100), nullable=True),
    sa.Column('plate_number', sa.String(length=50), nullable=True),
    sa.Column('mot_renewal_date', sa.Date(), nullable=True),
    sa.Column('mot_6_monthly_date', sa.Date(), nullable=True),
    sa.Column('plate_expiry_date', sa.Date(), nullable=True),
    sa.Column('tax_expiry_date', sa.Date(), nullable=True),
    sa.Column('insured', sa.Boolean(), nullable=True),
    sa.Column('vehicle_size', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('child_postcode', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('escort_id', sa.Integer(), nullable=True),
    sa.Column('driver_shift', sa.String(length=20), nullable=True),
    sa.Column('escort_shift', sa.String(length=20), nullable=True),
    sa.Column('contract_days', sa.String(length=100), nullable=True),
    sa.Column('repeat_all_week', sa.Boolean(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['escort_id'], ['escorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_card_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('litres', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('receipt_image', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mechanic_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('job_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('staff_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('mileage', sa.String(length=50), nullable=True),
    sa.Column('lights_ok', sa.Boolean(), nullable=True),
    sa.Column('tires_ok', sa.Boolean(), nullable=True),
    sa.Column('oil_level_ok', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('water_check', sa.Boolean(), nullable=True),
    sa.Column('mot_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missed_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('staff_name', sa.String(length=100), nullable=True),
    sa.Column('contract_number', sa.String(length=50), nullable=True),
    sa.Column('shift', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['driver_allocation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('staff_type', sa.String(length=50), nullable=True),
    sa.Column('run_date', sa.Date(), nullable=True),
    sa.Column('shift', sa.String(length=10), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['allocation_id'], ['driver_allocation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_status')
    op.drop_table('missed_run')
    op.drop_table('vehicle_check')
    op.drop_table('mechanic_jobs')
    op.drop_table('fuel_card_transaction')
    op.drop_table('driver_locations')
    op.drop_table('driver_allocation')
    op.drop_table('child')
    op.drop_table('vehicle')
    op.drop_table('tariff_rate')
    op.drop_table('school_term')
    op.drop_table('quote')
    op.drop_table('non_school_day')
    op.drop_table('missed_clock_out_request')
    op.drop_table('missed_clock_in_request')
    op.drop_table('mechanic')
    op.drop_table('manager')
    op.drop_table('leave')
    op.drop_table('inset_day')
    op.drop_table('feedback')
    op.drop_table('escorts')
    op.drop_table('drivers')
    op.drop_table('contract')
    op.drop_table('clock_in')
    # ### end Alembic commands ###
