"""Add completed_at and manager_confirmed to MechanicJob

Revision ID: fc04238e494b
Revises: ecec4e04f52d
Create Date: 2025-04-16 08:28:19.693483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc04238e494b'
down_revision = 'ecec4e04f52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('manager_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanic_jobs', schema=None) as batch_op:
        batch_op.drop_column('manager_confirmed')
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
